### ISSUE TITLE
Bunch of cosmetic cleanup

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_advancedreplace#69]
Mostly make it easier to glance and see whats going on, and tune the spacing so there is less wrapping of things we don't want to wrap

* [x] wrap the 100% is a badge, grey if not started, yellow if running, green if complete, red is broken (if we can tell this)
* [x] % should be 1 decimal point at most
* [x] `23 October 2024, 11:09 PM` -> `23 Oct 2024, 11:09pm` to save column width
* [x] Add line break instead of comma 'Components: mod_hvp, Mimetypes: application/zip.h5p, Open zips: 1'
* [ ] <del>sorting by id is identical to start, I think we can merge the id into the name column. eg `mod_hvp unfiltered (137)`</del>

**Comment by bwalkerl** [comment]
I've added these except the red badge for broken tasks (no link to task right now) and sorting by id (as this can be blank when it hasn't started). 

Realistically we could add start date earlier in the process, but if we add this the link to the tasks will be necessary.
